### ISSUE TITLE
Browsers on Android don't return keyCodes properly on the keydown event.

### ISSUE THREAD

**Issue by malcolmkiano** [malcolmkiano/decimal-input#1]
Browsers on Android return the keyCode 229 for pretty much everything and this creates an issue when the user tries to delete their entry. This also allows external input of the period "." which should not work under normal conditions.

I'm using an emulator, so that might be contributing to this issue, but I'm unsure.

**Comment by jgkiano** [comment]
I've encountered this issue before but luckily I had rx included in the project. What I did was pipe changes from the input to a stream then run some validation and manipulate the typed data if required. Finally i'd bind the value of the input to the output of the stream. I'm not sure if this pattern will help you though. As far as I can remember this has always been an issue for android.

**Comment by malcolmkiano** [comment]
> I've encountered this issue before but luckily I had rx included in the project. What I did was pipe changes from the input to a stream then run some validation and manipulate the typed data if required. Finally i'd bind the value of the input to the output of the stream. I'm not sure if this pattern will help you though. As far as I can remember this has always been an issue for android.

I'll attempt a fix based on this and get back. Thank you

**Comment by jgkiano** [comment]
Cool, let me know if it works out.

**Comment by malcolmkiano** [comment]
Instead of detecting keyCodes, passed old value and new value of inputs to a function to compare and determine the changes, then perform tasks based on the result of this.
