### ISSUE TITLE
If the input has a value, it doesn't convert well

### ISSUE THREAD

**Issue by martinzaleski** [malcolmkiano/decimal-input#3]
Hello!

I have an input with the value `30`.
When I run `decimalInput();` it converts the value to `300.00` instead of `30.00`.

It looks like it doesn't support pre-existing values at all.

Thank you so much, great library.
Best,
M

**Comment by malcolmkiano** [comment]
Hey @martinzaleski! Thanks for using the library! I'll take a look into this now!

**Comment by malcolmkiano** [comment]
This was resolved in [`ba21f64`](https://github.com/malcolmkiano/decimal-input/commit/ba21f648959d16f66842326f6892556ca36b893a)
